### PR TITLE
Fix indentation configuration

### LINKED ISSUE #289: [VSCODE] Prettier-SQL.tabSizeOverride not working
**Describe the bug**
I want to use a tab width with 4, but I can't find the proper settings

**To Reproduce**
check Prettier-SQL: Ignore Tab Settings
setting Prettier-SQL.tabSizeOverride to 4

1. Check Prettier-SQL: Ignore Tab Settings
2. Setting Prettier-SQL.tabSizeOverride to 4
3. Format with Shift + Alt + F
4. No matter how I change the settings, always format the file with tab width of 2

### PR DESCRIPTION
**Pull request by nene**
The extension used a long-outdated `indent` option. Replaced it with `tabWidth` and `useTabs` options.

Also changed the defaults:

- changed `tabSizeOverride` from `4` to `2`. So it aligns with SQL Formatter default. The previous versions of the extension have been stuck at the 2-space indentation (as the `indent` config had no effect).
- changed `ignoreTabSettings` to `false`, so vscode settings are used by default. This seems like a more sensible default, making it easier to change the tab size through editor (without having to wander inside the configs of this extension).

Performed several refactorings, just to make better sense of the code.

There's one bug still, which I haven't managed to figure out:

<del>When I change the indentation in current window (e.g. "Indent using spaces" -> "2") and run the command "Format Selection (Prettier SQL)", it doesn't use the newly configured indentation settings. However when I run "Format Document", it properly indents the code.</del>

<del>I tried to debug this and found that these incorrect values come from `vscode.workspace.getConfiguration('editor')`. My guess is that it's reading in the default editor configuration, not the active configuration of current window.</del>

Found a fix: Switched to `vscode.window.activeTextEditor.options` instead of `vscode.workspace.getConfiguration('editor')`.

Fixes https://github.com/sql-formatter-org/sql-formatter/issues/289

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -6,51 +6,58 @@ import {
...
+    denseOperators: extensionSettings.get<boolean>('denseOperators'),
+    newlineBeforeSemicolon: extensionSettings.get<boolean>('newlineBeforeSemicolon'),
   };
+};
 
-  return formatConfigs;
+const getIndentationConfig = (
+  extensionSettings: vscode.WorkspaceConfiguration,
+  formattingOptions: Partial<vscode.FormattingOptions>
+): Partial<FormatOptions> => {
```
Comment (inferrinizzard) [inline src/extension.ts:38]:
```suggestion
): Pick<FormatOptions, 'tabWidth' | 'useTabs'> => {
```

File: src/extension.ts [hunk 2]
```diff
@@ -6,51 +6,58 @@ import {
...
+    linesBetweenQueries: extensionSettings.get<number>('linesBetweenQueries'),
+    denseOperators: extensionSettings.get<boolean>('denseOperators'),
+    newlineBeforeSemicolon: extensionSettings.get<boolean>('newlineBeforeSemicolon'),
   };
+};
 
-  return formatConfigs;
+const getIndentationConfig = (
+  extensionSettings: vscode.WorkspaceConfiguration,
+  formattingOptions: Partial<vscode.FormattingOptions>
```
Comment (inferrinizzard) [inline src/extension.ts]: can we not just use FormattingOptions instead of partial for here and above ?

**Review by inferrinizzard — APPROVED** [review]

File: src/extension.ts (hunk 1 above)
Comment (nene) [reply src/extension.ts:38]: This doesn't typecheck. To be fully correct, we'd have to use `Partial<Pick<FormatOptions, 'tabWidth' | 'useTabs'>>` as the `WorkspaceConfiguration.get()` returns possibly `undefined`, but that's IMHO overkill.

File: src/extension.ts (hunk 2 above)
Comment (nene) [reply src/extension.ts]: Indeed, Partial not needed here. Will change.

**Comment by Anutrix** [comment]
When will this fix be released/available in the vscode extension marketplace?
